stages:
  prepare:
    cmd: python src/preprocessing.py
    deps:
      - data/heart_attack_prediction_indonesia.csv
      - src/preprocessing.py
    outs:
      - data/pipeline.pkl
      - data/processed_heart_attack_prediction.csv