apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
      - name: reddit-app
        image: us-west2-docker.pkg.dev/reddit-app-458423/reddit-repo/redditapp:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        command: ["uvicorn", "redditApp:app", "--host", "0.0.0.0", "--port", "8000"]
